kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-all-ingress
  namespace: zvps-system
spec:
  # 选择受保护的 Pod
  podSelector:
    matchLabels:
      app: zvps-super
  
  policyTypes:
    - Ingress
  
  # 允许入站规则
  ingress:
    - from: [] 
      ports:
        - protocol: UDP
          port: 2325 
        - protocol: UDP
          port: 2326 
