apiVersion: apps/v1
kind: Deployment
metadata:
  name: zvps-super
  namespace: zvps-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zvps-super
  template:
    metadata:
      labels:
        app: zvps-super
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: ubuntu-node
          image: ghcr.io/zv201413/zvps:latest 
          imagePullPolicy: Always
          env:
            - name: TTYD
              value: "admin:yourpassword123"  # Web终端密码
            - name: SSH_USER
              value: "zv"                    # SSH用户名
            - name: SSH_PWD
              value: "105106"                # SSH密码
            - name: GB
              value: "true"                  # 开启流量统计快捷键
          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"
          volumeMounts:
            - name: data-storage
              mountPath: /home/zv
      volumes:
        - name: data-storage
          persistentVolumeClaim:
            claimName: zvps-pvc

---
# 2. Service TCP: 处理 SSH (22) 和 Web (80 -> 7681)
apiVersion: v1
kind: Service
metadata:
  name: zvps-svc-tcp
  namespace: zvps-system
spec:
  type: LoadBalancer
  selector:
    app: zvps-super
  ports:
    - name: ssh-port
      protocol: TCP
      port: 22
      targetPort: 22
    - name: ttyd-port
      protocol: TCP
      port: 80
      targetPort: 7681

---
# 3. Service UDP: 处理 Hysteria 2 (2325) 和 TUIC (2326)
apiVersion: v1
kind: Service
metadata:
  name: zvps-svc-udp
  namespace: zvps-system
  annotations:
    # 必须有此注解，AWS 才会创建支持 UDP 的 NLB
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
spec:
  type: LoadBalancer
  selector:
    app: zvps-super
  ports:
    - name: hy-udp
      protocol: UDP
      port: 2325
      targetPort: 2325
    - name: tuic-udp
      protocol: UDP
      port: 2326
      targetPort: 2326
  externalTrafficPolicy: Cluster
